### ISSUE TITLE
Feed not showing up

### ISSUE THREAD

**Issue by hacker-DOM** [Benexl/yt-x#13]
I'm not sure if I'm doing something wrong but it's not working? 'Trending' comes up but not 'Your Feed', 'Channels' etc. Is there a way to enable a log?

**Comment by grossjonas** [comment]
For that to work you need to configure `yt-dlp`, see https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#configuration.
I used the cookie-way with the flatpak version of chrome ... like this
```
❯ cat --plain .config/yt-dlp/config
--cookies-from-browser chrome:~/.var/app/com.google.Chrome/
```
