### ISSUE TITLE
No Preview images

### ISSUE THREAD

**Issue by matzeruegge** [Benexl/yt-x#19]
I am on an up to date Arch Linux system with yt-x 0.3.3. I have installed all optional packages. Everything works fine except the preview images are not loaded. Any idea or hint is very preciated.

Kind regards
Matthias

My config is:

```
# whether to show colors when printing ouput
PRETTY_PRINT: true

# your preferred editor for editing your config
EDITOR: nano

# your preferred selector for the tui [fzf/rofi]
PREFERRED_SELECTOR: fzf

# the quality of the video when streaming with a player other than mpv
VIDEO_QUALITY: 1080

# whether to show previews [true/false]
# its cool so enable it
ENABLE_PREVIEW: true

# whether to run mpv as a background process and prevent it from closing even if you terminate the program or terminal session
DISOWN_STREAMING_PROCESS: true

# whether to update the recent list kept locally [true/false]
UPDATE_RECENT: true

# the number of recent videos to keep
NO_OF_RECENT: 30

# the player to use for streaming [mpv/vlc]
PLAYER: mpv

# the browser to use to extract cookies from
# this is used to by yt-dlp to access content that would require login
PREFERRED_BROWSER: firefox

# the number of results to get from yt-dlp
NO_OF_SEARCH_RESULTS: 30

# the duration notifications stay on the screen
NOTIFICATION_DURATION: 5

# where your downloads will be stored
DOWNLOAD_DIRECTORY: /home/yt/Videos/yt-x

```

**Comment by Benexl** [comment]
Are you running the dev version or release.
In either case make sure there are no spaces after true and only one BTW the colon and true.

**Comment by matzeruegge** [comment]
I am running the dev version. The config looks fine. I can see the images and text files downloaded in the .cache directory. The error message in the gui is: caught panic: provided file is not a console restoring terminal ... 
![grafik](https://github.com/user-attachments/assets/58007327-2b4f-4207-a3b2-43d5c34144df)

**Comment by Benexl** [comment]
Thats new what terminal is that

**Comment by matzeruegge** [comment]
![grafik](https://github.com/user-attachments/assets/4572e28b-cefa-4031-b371-45c4f53014ce)

**Comment by matzeruegge** [comment]
It is terminal related. Looks perfect with kitty. Preview is loaded and also the little icons in the menu are displayed.

**Comment by Benexl** [comment]
okey gonna close it then

**Comment by matzeruegge** [comment]
Sure. Maybe you can mention kitty in the installation instructions.

**Comment by Benexl** [comment]
Nah, it should work on the modern terminals like also wezterm and the likes, maybe I'll add a modern terminal to readme

But in most cases people who do use and prefer terminal tools already have a modern terminal.

But I'll still add it.
