### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by omnigenous** [Benexl/yt-x#2]
https://aur.archlinux.org/

Please, consider publishing to Arch User Repositories!

**Comment by Benex254** [comment]
I don't know how to do that and i use nixos. So it will probably come first. Though if you can do it for me would appreciate

**Comment by tikisri** [comment]
nixos pkg when?

**Comment by Benex254** [comment]
Well am very busy this days, so not sure. Though when am free I'll definitely do it.
