### ISSUE TITLE
Search is fucked....

### ISSUE THREAD

**Issue by NischalDawadi** [Benexl/yt-x#20]
It shows irrelevant video even if the title is same....
![image](https://github.com/user-attachments/assets/8a98e198-6e2e-46ee-98a0-93bdead703d5)Youtube
![image](https://github.com/user-attachments/assets/afc68c2a-29b9-4242-bc6e-0cafa697fc39)yt-x
It started after updating to newer version

**Comment by Benexl** [comment]
Remember its the youtube algorithm thats used and its not only your intentended title thats labled that way. It may help to set `PREFERRED_BROWSER:` so it can use your cookies and make the search more personalised

**Comment by NischalDawadi** [comment]
![image](https://github.com/user-attachments/assets/30119a89-d03d-4c23-a4b6-109c967ce2cb)
Its working well for v0.3.3

**Comment by Benexl** [comment]
Okey try deleting your config and setting it up again. Cause there's nothing major i have changed when it comes to search you can check for yourself. Tell me if it works

**Comment by Benexl** [comment]
In my case when i searched i got it, without login. Maybe you as the user changed your preferences over the weeks lol. But seriously am stumped with this one. Though am sure it is not yt-x too blame. Maybe yt-dlp which fetches the data
![image](https://github.com/user-attachments/assets/abee750d-b51f-4859-89a1-540a5f2ce7d9)

**Comment by NischalDawadi** [comment]
I don't know what's wrong with mine.. 
Will stick to older version as it's working fine..

**Comment by Benexl** [comment]
Okey i figured it out it is yt-x to blame. The prompt function has issues after trying to make read posix compliant. Try installing gum and everything should be okey as i come up with a fix.

**Comment by Benexl** [comment]
Fixed by the latest commit : )

**Comment by NischalDawadi** [comment]
That was quite fast.. Thank you
