### ISSUE TITLE
Seriously amazing work. Am I allowed to produce a self-contained, portable, version of this?

### ISSUE THREAD

**Issue by xplshn** [Benexl/yt-x#7]
Hi! Amazing work right here! Super slim. I'd like to produce an AppBundle of your program, am I allowed to do so?

I'd like you to make it official, like, release them in this repo.

An AppBundle is a portable format like AppImages, but it lets you do a lot more because it doesn't enforce a spec like the AppDir spec, which is kind of cumbersome, specially if you want to ship more than one binary within it.

I can provide a script that generates an AppBundle for you, I'd just like it to be added in the releases :)

It'd be a `quick start` way, for people that don't want to have to install yt-dlp and all of its python deps on their system, or Alpine users like me who don't want to have to install `bash` or anything else

**Comment by xplshn** [comment]
![image](https://github.com/user-attachments/assets/8c1153f3-5515-4422-a475-8ecfe9820bdd)
`ffmpeg` is really big. But that's it, that's a portable AppBundle of `yt-x` :)

**Comment by xplshn** [comment]
[yt-x.txt](https://github.com/user-attachments/files/17911772/yt-x.txt)
I tried to fix an issue I'm getting wiht `yt-x`, both in the AppBundle and in a normal install, and that is:
> /usr/local/bin/yt-x: line 217: `fzf-preview': not a valid identifier

I'm not sure what this means.

And btw, taking a look at your code, it is mostly POSIX, with the exception of using unnecessary bash syntax, it'd be amazing if you made it POSIX `sh`, its not that far from being POSIX actually. No actual bash features apart from array slicing are being used. (which is something that can be done in `sh` slightly differently)

**Comment by Benexl** [comment]
Its definitely that, if its not am not sure what could be the issue, don't really know much on ash

**Comment by xplshn** [comment]
Hmm, its an issue with `yt-x` itself.
![image](https://github.com/user-attachments/assets/5bd47c9c-16a8-47ab-b0d9-abf561da294c)

**Comment by Benexl** [comment]
Yeah thats what i said, `fzf-preview` is not recongnized as a valid function identifier in posixx

**Comment by xplshn** [comment]
> Yeah thats what i said, `fzf-preview` is not recongnized as a valid function identifier in posixx Cause of the hyphen, hopefully i'll be able to change it later

I ran this in `bash`, without tweaks or anything, and it does not work, same error message

**Comment by Benexl** [comment]
Try changing the name to fzf_preview if you don't believe me

**Comment by xplshn** [comment]
> Try changing the name to fzf_preview if you don't believe me

Its not that I don't believe you. I downloaded the program, installed the necessary cli tools, and ran it, and it simply did not run as expected. I'll revisit once you fix your project. I don't understand why you didn't do it already if you know the solution... Is there anything keeping you from doing this?

**Comment by Benexl** [comment]
I told you thats cause of posix compatibility i'll do that later. If it was not working don't you think there would be more issues

**Comment by Benexl** [comment]
You do realize, you could try debugging the issue yourself then submit a pr. It would be impossible for me to replicate the issue and I myself am not experincing the issue.

**Comment by xplshn** [comment]
> You do realize, you could try debugging the issue yourself then submit a pr. It would be impossible for me to replicate the issue and I myself am not experincing the issue.

It was fixed with the commit made 4 hours ago. I'll make the recipe available in AppBundleHUB, and add an action here so that you can build these two:
yt-x-ffmpeg.dwfs.AppBundle (will be heavier)
yt-x.dwfs.AppBundle (doesn't come with ffmpeg)

(the user won't need yt-dlp, or any other dependencies)

**Comment by Benexl** [comment]
Changed my mind on them. Don't see them being used a lot in the linux community. People prefer using there distros package managers.

**Comment by xplshn** [comment]
Its up to you, if you'd like to offer your users with a quick way to set up, without having to install python, without having to get yt-dlp, without needing to get `bash`, without needing to install `ffmpeg`... Its already available in https://github.com/xplshn/AppBundleHUB

![image](https://github.com/user-attachments/assets/368ff56e-79e3-42f8-8d18-ec427b7487b7)

I just changed the compression options of `dwarfs`, so I've triggered a re-release, in about 20 minutes, the new release should have a smaller `yt-x` (I hope, because to the new release, not only did I change the compression options, I also added ffmpeg, which weights a lot, 37 megs is the weight of yt-dlp when standalone (single binary that doesn't need python) and ffmpeg weights 76megs)

![image](https://github.com/user-attachments/assets/6fdcc1c4-7a09-4132-95bd-18e87c653b2c)
