### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by NischalDawadi** [Benexl/yt-x#8]
https://github.com/user-attachments/assets/b5ebc67a-44c0-4749-a944-e2b8a7308a1a

**Comment by NischalDawadi** [comment]
https://github.com/user-attachments/assets/441bab5f-2f4b-47e3-b769-6c880874bfc0

Ok now what is wrong then?

**Comment by Benexl** [comment]
The parser is pretty basic and it seems you left a space after the x.
![image](https://github.com/user-attachments/assets/f249ffb3-bef2-48fb-9f3c-35eaea98b6d1)

**Comment by NischalDawadi** [comment]
I tried it didn't work.

**Comment by Benexl** [comment]
Thats the issue though. If it was not working for everyone don't you think there would be more issues being opened. If you want further assistance join the discord. Cause the only issue i could infer from your video is that, i even showed you the exact frame when the error was being displayed which was not easy to get.

**Comment by NischalDawadi** [comment]
I was fucking stupid, i just thought it should be after comma and didn't realise that there should be no space after firefox as well. Sorry.And thanks..
